R CMD BATCH --no-save weekly-TAT-4-LOD-10.R
R CMD BATCH --no-save weekly-TAT-4-LOD-103.R
R CMD BATCH --no-save weekly-TAT-4-LOD-105.R
R CMD BATCH --no-save weekly-TAT-5-LOD-10.R
R CMD BATCH --no-save weekly-TAT-5-LOD-103.R
R CMD BATCH --no-save weekly-TAT-5-LOD-105.R
R CMD BATCH --no-save weekly-TAT-10-LOD-10.R
R CMD BATCH --no-save weekly-TAT-10-LOD-103.R
R CMD BATCH --no-save weekly-TAT-10-LOD-105.R
