R CMD BATCH --no-save two-week-2-test-days-trace-1-symp-group.R
R CMD BATCH --no-save two-week-2-test-days-trace-1-symp.R
R CMD BATCH --no-save two-week-2-test-days-trace-1.R
R CMD BATCH --no-save two-week-2-test-days.R
R CMD BATCH --no-save two-week-5-test-days-trace-1-symp-group.R
R CMD BATCH --no-save two-week-5-test-days-trace-1-symp.R
R CMD BATCH --no-save two-week-5-test-days-trace-1.R
R CMD BATCH --no-save two-week-5-test-days.R
R CMD BATCH --no-save two-week-7-test-days-trace-1-symp-group.R
R CMD BATCH --no-save two-week-7-test-days-trace-1-symp.R
R CMD BATCH --no-save two-week-7-test-days-trace-1.R
R CMD BATCH --no-save two-week-7-test-days.R
