R CMD BATCH --no-save biweekly-TAT-1-LOD-10-trace.R
R CMD BATCH --no-save biweekly-TAT-2-LOD-10-trace.R
R CMD BATCH --no-save biweekly-TAT-3-LOD-10-trace.R
R CMD BATCH --no-save biweekly-TAT-4-LOD-10-trace.R
R CMD BATCH --no-save biweekly-TAT-5-LOD-10-trace.R
R CMD BATCH --no-save biweekly-TAT-10-LOD-10-trace.R
R CMD BATCH --no-save weekly-TAT-1-LOD-10-trace.R
R CMD BATCH --no-save weekly-TAT-2-LOD-10-trace.R
R CMD BATCH --no-save weekly-TAT-3-LOD-10-trace.R
R CMD BATCH --no-save weekly-TAT-4-LOD-10-trace.R
R CMD BATCH --no-save weekly-TAT-5-LOD-10-trace.R
R CMD BATCH --no-save weekly-TAT-10-LOD-10-trace.R
R CMD BATCH --no-save two-week-TAT-1-LOD-10-trace.R
R CMD BATCH --no-save two-week-TAT-2-LOD-10-trace.R
R CMD BATCH --no-save two-week-TAT-3-LOD-10-trace.R
R CMD BATCH --no-save two-week-TAT-4-LOD-10-trace.R
R CMD BATCH --no-save two-week-TAT-5-LOD-10-trace.R
R CMD BATCH --no-save two-week-TAT-10-LOD-10-trace.R
