R CMD BATCH --no-save TAT-1-LOD-10.R
R CMD BATCH --no-save TAT-1-LOD-103.R
R CMD BATCH --no-save TAT-1-LOD-105.R
R CMD BATCH --no-save TAT-2-LOD-10.R
R CMD BATCH --no-save TAT-2-LOD-103.R
R CMD BATCH --no-save TAT-2-LOD-105.R
R CMD BATCH --no-save TAT-3-LOD-10.R
R CMD BATCH --no-save TAT-3-LOD-103.R
R CMD BATCH --no-save TAT-3-LOD-105.R



